# Generated by Django 6.0.4 on 2026-05-08 05:51

import apps.admin_master.models
import django.db.models.deletion
from django.contrib.auth.hashers import identify_hasher, make_password
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def build_unique_code(model, seed_value, *, pk=None, prefix="master", max_length=100):
    base = slugify(seed_value or "")[:max_length].strip("-") or prefix
    candidate = base
    counter = 2

    queryset = model.objects.all()
    if pk:
        queryset = queryset.exclude(pk=pk)

    while queryset.filter(code=candidate).exists():
        suffix = f"-{counter}"
        candidate = f"{base[: max_length - len(suffix)]}{suffix}"
        counter += 1

    return candidate


def split_full_name(full_name):
    parts = [part for part in (full_name or "").strip().split() if part]
    if not parts:
        return "", ""
    if len(parts) == 1:
        return parts[0], ""
    return parts[0], " ".join(parts[1:])


def to_stored_password(raw_password):
    if not raw_password:
        return raw_password
    try:
        identify_hasher(raw_password)
        return raw_password
    except Exception:
        return make_password(raw_password)


def migrate_legacy_admin_master_data(apps, schema_editor):
    auth_app_label, auth_model_name = settings.AUTH_USER_MODEL.split(".")
    UserModel = apps.get_model(auth_app_label, auth_model_name)
    MainScreen = apps.get_model("admin_master", "MainScreen")
    ScreenSection = apps.get_model("admin_master", "ScreenSection")
    Staff = apps.get_model("admin_master", "Staff")
    UserCreation = apps.get_model("admin_master", "UserCreation")
    UserScreen = apps.get_model("admin_master", "UserScreen")
    UserType = apps.get_model("admin_master", "UserType")
    UserTypePermission = apps.get_model("admin_master", "UserTypePermission")

    for index, main_screen in enumerate(MainScreen.objects.order_by("id"), start=1):
        update_fields = []
        if main_screen.order_no != index:
            main_screen.order_no = index
            update_fields.append("order_no")
        if not main_screen.code:
            main_screen.code = build_unique_code(MainScreen, main_screen.name, pk=main_screen.pk, prefix="main-screen")
            update_fields.append("code")
        if update_fields:
            main_screen.save(update_fields=update_fields)

    section_sequence_by_screen = {}
    for section in ScreenSection.objects.select_related("main_screen").order_by("main_screen_id", "id"):
        counter = section_sequence_by_screen.get(section.main_screen_id, 0) + 1
        section_sequence_by_screen[section.main_screen_id] = counter

        update_fields = []
        if section.order_no != counter:
            section.order_no = counter
            update_fields.append("order_no")
        if not section.code:
            section.code = build_unique_code(
                ScreenSection,
                f"{section.main_screen.name}-{section.name}",
                pk=section.pk,
                prefix="screen-section",
            )
            update_fields.append("code")
        if update_fields:
            section.save(update_fields=update_fields)

    for index, staff in enumerate(Staff.objects.order_by("id"), start=1):
        if not staff.staff_code:
            staff.staff_code = f"{index:04d}"
            staff.save(update_fields=["staff_code"])

    for user_type in UserType.objects.order_by("id"):
        if not user_type.code:
            user_type.code = build_unique_code(UserType, user_type.name, pk=user_type.pk, prefix="user-type")
            user_type.save(update_fields=["code"])

    for screen in UserScreen.objects.select_related("main_screen", "screen_section").order_by("id"):
        legacy_actions = []
        if screen.can_add:
            legacy_actions.append("add")
        if screen.can_update:
            legacy_actions.append("update")
        if screen.can_list:
            legacy_actions.append("list")
        if screen.can_delete:
            legacy_actions.append("delete")
        if screen.can_view:
            legacy_actions.append("view")
        if screen.can_print:
            legacy_actions.append("print")
        if not legacy_actions:
            legacy_actions = ["list", "view"]

        update_fields = ["available_actions"]
        screen.available_actions = legacy_actions
        if not screen.code:
            screen.code = build_unique_code(
                UserScreen,
                screen.folder_name or screen.screen_name,
                pk=screen.pk,
                prefix="screen",
            )
            update_fields.append("code")
        screen.save(update_fields=update_fields)

    for user_creation in UserCreation.objects.select_related("staff").order_by("id"):
        auth_user = UserModel.objects.filter(username=user_creation.username).first()
        if not auth_user:
            auth_user = UserModel(username=user_creation.username)

        auth_user.is_active = user_creation.is_active
        auth_user.password = to_stored_password(user_creation.password)

        if getattr(user_creation.staff, "email", None):
            auth_user.email = user_creation.staff.email

        first_name, last_name = split_full_name(getattr(user_creation.staff, "name", ""))
        if not getattr(auth_user, "first_name", ""):
            auth_user.first_name = first_name
        if not getattr(auth_user, "last_name", ""):
            auth_user.last_name = last_name

        auth_user.save()

        if user_creation.staff_id and user_creation.mobile and not user_creation.staff.mobile:
            user_creation.staff.mobile = user_creation.mobile
            user_creation.staff.save(update_fields=["mobile"])

        if user_creation.department_id and user_creation.staff_id and not user_creation.staff.department_id:
            user_creation.staff.department_id = user_creation.department_id
            user_creation.staff.save(update_fields=["department"])

        update_fields = [
            "user",
            "account_status",
            "failed_login_attempts",
            "force_password_change",
        ]
        user_creation.user_id = auth_user.pk
        user_creation.account_status = "active" if user_creation.is_active else "inactive"
        user_creation.failed_login_attempts = 0
        user_creation.force_password_change = False

        if user_creation.password and not user_creation.password_changed_at:
            user_creation.password_changed_at = user_creation.created_at
            update_fields.append("password_changed_at")

        user_creation.save(update_fields=update_fields)

    for permission in UserTypePermission.objects.order_by("id"):
        permission.scope_type = "main_screen"
        permission.screen_section_id = None
        permission.user_screen_id = None
        permission.permission_key = f"{permission.user_type_id}:main_screen:{permission.main_screen_id}"
        permission.action_permissions = {
            "all": False,
            "add": bool(permission.can_add),
            "update": bool(permission.can_edit),
            "list": bool(permission.can_view),
            "delete": bool(permission.can_delete),
            "view": bool(permission.can_view),
            "print": False,
        }
        permission.save(
            update_fields=[
                "scope_type",
                "screen_section",
                "user_screen",
                "permission_key",
                "action_permissions",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0001_initial'),
        ('common_master', '0001_initial'),
        ('login_home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainscreen',
            options={'ordering': ['order_no', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='screensection',
            options={'ordering': ['main_screen_id', 'order_no', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['staff_code', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='ticketusertype',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='usercreation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userscreen',
            options={'ordering': ['main_screen_id', 'screen_section_id', 'order_no', 'screen_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='usertypepermission',
            options={'ordering': ['user_type_id', 'main_screen_id', 'screen_section_id', 'user_screen_id', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='usertypepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mainscreen',
            name='order_no',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='screensection',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='screensection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screensection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='screensection',
            name='order_no',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='login_home.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_code',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usercreation',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('locked', 'Locked')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='usercreation',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercreation',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercreation',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercreation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercreation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userscreen',
            name='available_actions',
            field=models.JSONField(default=apps.admin_master.models.default_screen_actions),
        ),
        migrations.AddField(
            model_name='userscreen',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userscreen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertypepermission',
            name='action_permissions',
            field=models.JSONField(default=apps.admin_master.models.default_action_permissions),
        ),
        migrations.AddField(
            model_name='usertypepermission',
            name='permission_key',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usertypepermission',
            name='scope_type',
            field=models.CharField(choices=[('main_screen', 'Main Screen'), ('section', 'Section'), ('screen', 'Screen')], db_index=True, default='screen', max_length=20),
        ),
        migrations.AddField(
            model_name='usertypepermission',
            name='screen_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='admin_master.screensection'),
        ),
        migrations.AddField(
            model_name='usertypepermission',
            name='user_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='admin_master.userscreen'),
        ),
        migrations.AlterField(
            model_name='mainscreen',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mainscreen',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='mainscreen',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='screensection',
            name='main_screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='admin_master.mainscreen'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='ticketusertype',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='common_master.company'),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_user_accounts', to='login_home.department'),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='admin_master.role'),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accounts', to='admin_master.staff'),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='managed_by', to='admin_master.usercreation'),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='ticket_user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='admin_master.ticketusertype'),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_accounts', to='admin_master.usertype'),
        ),
        migrations.AlterField(
            model_name='userscreen',
            name='folder_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userscreen',
            name='main_screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_screens', to='admin_master.mainscreen'),
        ),
        migrations.AlterField(
            model_name='userscreen',
            name='order_no',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userscreen',
            name='screen_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_screens', to='admin_master.screensection'),
        ),
        migrations.AlterField(
            model_name='usertypepermission',
            name='main_screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='admin_master.mainscreen'),
        ),
        migrations.AlterField(
            model_name='usertypepermission',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='admin_master.usertype'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['name'], name='staff_name_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['mobile'], name='staff_mobile_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreation',
            index=models.Index(fields=['user_type', 'account_status'], name='user_acc_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreation',
            index=models.Index(fields=['company', 'department'], name='user_acc_org_idx'),
        ),
        migrations.AddIndex(
            model_name='userscreen',
            index=models.Index(fields=['main_screen', 'screen_section', 'is_active'], name='usr_screen_scope_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userscreen',
            index=models.Index(fields=['screen_name'], name='usr_screen_name_idx'),
        ),
        migrations.AddIndex(
            model_name='usertypepermission',
            index=models.Index(fields=['user_type', 'scope_type', 'status'], name='usr_perm_type_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='usertypepermission',
            index=models.Index(fields=['main_screen', 'status'], name='usr_perm_main_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usertypepermission',
            index=models.Index(fields=['user_screen', 'status'], name='usr_perm_screen_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='screensection',
            constraint=models.UniqueConstraint(fields=('main_screen', 'name'), name='unique_screen_section_per_main_screen'),
        ),
        migrations.AddConstraint(
            model_name='userscreen',
            constraint=models.UniqueConstraint(fields=('main_screen', 'screen_section', 'screen_name'), name='unique_user_screen_per_section'),
        ),
        migrations.RunPython(migrate_legacy_admin_master_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='usercreation',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='usercreation',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usercreation',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userscreen',
            name='can_add',
        ),
        migrations.RemoveField(
            model_name='userscreen',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='userscreen',
            name='can_list',
        ),
        migrations.RemoveField(
            model_name='userscreen',
            name='can_print',
        ),
        migrations.RemoveField(
            model_name='userscreen',
            name='can_update',
        ),
        migrations.RemoveField(
            model_name='userscreen',
            name='can_view',
        ),
        migrations.RemoveField(
            model_name='usertypepermission',
            name='can_add',
        ),
        migrations.RemoveField(
            model_name='usertypepermission',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='usertypepermission',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='usertypepermission',
            name='can_view',
        ),
    ]
