# Generated by Django 6.0.4 on 2026-05-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0004_rename_user_admin_screens'),
        ('wpe_masters', '0006_seed_product_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='company_wise',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='department_wise',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='project_wise',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='under_users',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user_wise',
        ),
        migrations.AddField(
            model_name='usertype',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_user_types', to='wpe_masters.departmentmaster'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_user_types', to='wpe_masters.rolemaster'),
        ),
        migrations.AddConstraint(
            model_name='usertype',
            constraint=models.UniqueConstraint(fields=('department', 'role'), name='admin_user_type_department_role_uniq'),
        ),
    ]
