# Generated by Django 6.0.4 on 2026-06-05 05:31

import apps.admin_master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0005_remove_usertype_company_wise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.admin_master.models.staff_photo_upload_path),
        ),
        migrations.AddField(
            model_name='staff',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
