# Generated by Django 6.0.4 on 2026-06-05 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0006_add_staff_creation_fields'),
        ('wpe_masters', '0009_ensure_blend_production_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='wpe_masters.departmentmaster'),
        ),
        migrations.AddField(
            model_name='staff',
            name='role_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='wpe_masters.rolemaster'),
        ),
    ]
