# Generated by Django 6.0.4 on 2026-06-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0012_merge_0011_admin_master_branches'),
        ('admin_master', '0013_staff_designation_master'),
    ]

    operations = [
    ]
