# Generated by Django 6.0.4 on 2026-06-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0014_merge_20260610_0534'),
        ('admin_master', '0014_merge_20260610_0955'),
    ]

    operations = [
    ]
