# Generated by Django 6.0.4 on 2026-06-19 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleBridgeReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('workstation_id', models.CharField(db_index=True, max_length=100)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(default='kg', max_length=16)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('no_serial_port', 'No Serial Port'), ('invalid_reading', 'Invalid Reading'), ('bridge_not_reporting', 'Bridge Not Reporting')], default='disconnected', max_length=32)),
                ('raw_value', models.TextField(blank=True)),
                ('source', models.CharField(default='local_bridge', max_length=32)),
                ('detected_port', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at', 'device_id'],
                'indexes': [models.Index(fields=['workstation_id', 'last_seen_at'], name='scale_bridge_ws_seen_idx')],
            },
        ),
    ]
