# Generated by Django 6.0.4 on 2026-06-26 00:00

from django.db import migrations, models


def populate_legacy_bridge_client_ids(apps, schema_editor):
    ScaleBridgeReading = apps.get_model("scale", "ScaleBridgeReading")
    for reading in ScaleBridgeReading.objects.filter(bridge_client_id=""):
        reading.bridge_client_id = f"legacy:{reading.workstation_id}:{reading.device_id}"
        reading.save(update_fields=["bridge_client_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("scale", "0003_scale_status_stable_unstable"),
    ]

    operations = [
        migrations.AddField(
            model_name="scalebridgereading",
            name="bridge_client_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.RunPython(populate_legacy_bridge_client_ids, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="scalebridgereading",
            name="scale_bridge_device_workstation_unique",
        ),
        migrations.RemoveIndex(
            model_name="scalebridgereading",
            name="scale_bridge_device_ws_idx",
        ),
        migrations.RemoveIndex(
            model_name="scalebridgereading",
            name="scale_bridge_ws_seen_idx",
        ),
        migrations.AddConstraint(
            model_name="scalebridgereading",
            constraint=models.UniqueConstraint(
                fields=("device_id", "workstation_id", "bridge_client_id"),
                name="scale_bridge_device_workstation_client_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="scalebridgereading",
            index=models.Index(
                fields=("device_id", "workstation_id", "bridge_client_id"),
                name="scale_br_dev_ws_cli_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scalebridgereading",
            index=models.Index(
                fields=("workstation_id", "bridge_client_id", "last_seen_at"),
                name="scale_br_ws_cli_seen_idx",
            ),
        ),
    ]
