# Generated by Django 6.0.4 on 2026-05-08 07:50

import apps.common_master.services
import django.core.validators
import django.db.models.deletion
import re
import uuid
from decimal import Decimal
from django.db import migrations, models


def migrate_country_currency_to_currency(apps, schema_editor):
    Country = apps.get_model("common_master", "Country")
    Currency = apps.get_model("common_master", "Currency")

    for country in Country.objects.exclude(currency__isnull=True).exclude(currency=""):
        raw_value = str(country.currency).strip()
        if not raw_value:
            continue

        code = re.sub(r"[^A-Z0-9]", "", raw_value.upper())[:10] or f"CUR{country.id}"
        Currency.objects.get_or_create(
            country_id=country.id,
            code=code,
            defaults={
                "name": raw_value,
                "is_active": bool(country.status),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('common_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'common_master_currency',
                'ordering': ['name', 'code', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('customer_no', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('customer_group', models.CharField(choices=[('international', 'International'), ('domestic', 'Domestic')], db_index=True, max_length=20)),
                ('customer_division', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_no', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('gst_registered', models.BooleanField(default=False)),
                ('gst_provisional', models.BooleanField(default=False)),
                ('customer_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], db_index=True, default='active', max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_since', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'common_master_customer',
                'ordering': ['customer_name', 'customer_no', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('provisional', 'Provisional')], default='unregistered', max_length=20)),
                ('ecc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('same_as_billing', models.BooleanField(default=False)),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], db_index=True, max_length=20)),
            ],
            options={
                'db_table': 'common_master_customer_address',
                'ordering': ['address_type', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_address', models.TextField(blank=True, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('beneficiary_account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=34)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'common_master_customer_bank',
                'ordering': ['-is_primary', 'bank_name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person_name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'common_master_customer_contact',
                'ordering': ['contact_person_name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(db_index=True, max_length=50)),
                ('file', models.FileField(upload_to=apps.common_master.services.customer_document_upload_path)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'common_master_customer_document',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerStatutoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ecc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('commissionerate', models.CharField(blank=True, max_length=150, null=True)),
                ('division', models.CharField(blank=True, max_length=150, null=True)),
                ('range_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('tin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('service_tax_no', models.CharField(blank=True, max_length=50, null=True)),
                ('iec_code', models.CharField(blank=True, max_length=50, null=True)),
                ('cin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('tan_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'common_master_customer_statutory',
                'ordering': ['customer_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('supplier_no', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('supplier_name', models.CharField(db_index=True, max_length=255)),
                ('supplier_group', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('corporate_address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('gst_registration_date', models.DateField(blank=True, null=True)),
                ('gst_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('provisional', 'Provisional')], default='unregistered', max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('msme_type', models.CharField(choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20)),
                ('arn_no', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('vendor_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'common_master_supplier',
                'ordering': ['supplier_name', 'supplier_no', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('provisional', 'Provisional')], default='unregistered', max_length=20)),
                ('ecc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('same_as_billing', models.BooleanField(default=False)),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], db_index=True, max_length=20)),
            ],
            options={
                'db_table': 'common_master_supplier_address',
                'ordering': ['address_type', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=34)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('bank_address', models.TextField(blank=True, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'common_master_supplier_bank',
                'ordering': ['-is_primary', 'bank_name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person_name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'common_master_supplier_contact',
                'ordering': ['contact_person_name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(db_index=True, max_length=50)),
                ('file', models.FileField(upload_to=apps.common_master.services.supplier_document_upload_path)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'common_master_supplier_document',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierStatutoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ecc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('commissionerate', models.CharField(blank=True, max_length=150, null=True)),
                ('division', models.CharField(blank=True, max_length=150, null=True)),
                ('range_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('tin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('service_tax_no', models.CharField(blank=True, max_length=50, null=True)),
                ('iec_code', models.CharField(blank=True, max_length=50, null=True)),
                ('cin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('tan_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'common_master_supplier_statutory',
                'ordering': ['supplier_id'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='commonmaster',
            options={'ordering': ['type', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['order_no', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['name', 'id']},
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='cm_city_state_idx',
            old_name='common_mast_state_i_9d388c_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='cm_city_name_idx',
            old_name='common_mast_name_65887a_idx',
        ),
        migrations.RenameIndex(
            model_name='tax',
            new_name='cm_tax_name_idx',
            old_name='common_mast_name_e36785_idx',
        ),
        migrations.RenameIndex(
            model_name='tax',
            new_name='cm_tax_country_idx',
            old_name='common_mast_country_a2b657_idx',
        ),
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencies', to='common_master.country'),
        ),
        migrations.RunPython(migrate_country_currency_to_currency, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
        migrations.AddField(
            model_name='continent',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='order_no',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonmaster',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='commonmaster',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commonmaster',
            name='type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='common_master.city'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='common_master.country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=apps.common_master.services.company_document_upload_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common_master.services.company_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='pincode',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='common_master.state'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='continent',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='common_master.city'),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='common_master.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pincode',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='common_master.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tax',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tax',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country', 'pincode'], name='cm_city_country_pin_idx'),
        ),
        migrations.AddIndex(
            model_name='commonmaster',
            index=models.Index(fields=['type', 'is_active'], name='cm_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['code'], name='cm_company_code_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['continent', 'status'], name='cm_country_cont_st_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['code'], name='cm_country_code_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='cm_project_code_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country', 'is_active'], name='cm_state_country_act_idx'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_city_set', to='common_master.city'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_set', to='common_master.country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='common_master.currency'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_state_set', to='common_master.state'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_city_set', to='common_master.city'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_set', to='common_master.country'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='common_master.customer'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_state_set', to='common_master.state'),
        ),
        migrations.AddField(
            model_name='customerbankdetail',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='common_master.customer'),
        ),
        migrations.AddField(
            model_name='customercontactperson',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='common_master.customer'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='common_master.customer'),
        ),
        migrations.AddField(
            model_name='customerstatutorydetail',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_detail', to='common_master.customer'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_city_set', to='common_master.city'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_set', to='common_master.country'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='common_master.currency'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_state_set', to='common_master.state'),
        ),
        migrations.AddField(
            model_name='supplieraddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_city_set', to='common_master.city'),
        ),
        migrations.AddField(
            model_name='supplieraddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country_set', to='common_master.country'),
        ),
        migrations.AddField(
            model_name='supplieraddress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_state_set', to='common_master.state'),
        ),
        migrations.AddField(
            model_name='supplieraddress',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='common_master.supplier'),
        ),
        migrations.AddField(
            model_name='supplierbankdetail',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='common_master.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercontactperson',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='common_master.supplier'),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='common_master.supplier'),
        ),
        migrations.AddField(
            model_name='supplierstatutorydetail',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_detail', to='common_master.supplier'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['country', 'is_active'], name='cm_curr_country_act_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='cm_curr_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='cm_curr_country_name_uq'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('country', 'code'), name='cm_curr_country_code_uq'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_group', 'customer_status'], name='cm_customer_grp_st_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['country', 'state', 'city'], name='cm_customer_geo_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_no'], name='cm_customer_no_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('customer_name', 'country'), name='cm_customer_name_ct_uq'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['customer', 'address_type'], name='cm_cust_addr_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(fields=('customer', 'address_type'), name='cm_cust_addr_type_uq'),
        ),
        migrations.AddIndex(
            model_name='customerbankdetail',
            index=models.Index(fields=['customer', 'is_active'], name='cm_cust_bank_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerbankdetail',
            constraint=models.UniqueConstraint(fields=('customer', 'account_number'), name='cm_cust_bank_acct_uq'),
        ),
        migrations.AddIndex(
            model_name='customercontactperson',
            index=models.Index(fields=['customer', 'is_active'], name='cm_cust_contact_act_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdocument',
            index=models.Index(fields=['customer', 'document_type'], name='cm_cust_doc_type_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['country', 'state', 'city'], name='cm_supplier_geo_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_no'], name='cm_supplier_no_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('supplier_name', 'country'), name='cm_supplier_name_ct_uq'),
        ),
        migrations.AddIndex(
            model_name='supplieraddress',
            index=models.Index(fields=['supplier', 'address_type'], name='cm_supp_addr_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplieraddress',
            constraint=models.UniqueConstraint(fields=('supplier', 'address_type'), name='cm_supp_addr_type_uq'),
        ),
        migrations.AddIndex(
            model_name='supplierbankdetail',
            index=models.Index(fields=['supplier', 'is_active'], name='cm_supp_bank_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierbankdetail',
            constraint=models.UniqueConstraint(fields=('supplier', 'account_number'), name='cm_supp_bank_acct_uq'),
        ),
        migrations.AddIndex(
            model_name='suppliercontactperson',
            index=models.Index(fields=['supplier', 'is_active'], name='cm_supp_contact_act_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdocument',
            index=models.Index(fields=['supplier', 'document_type'], name='cm_supp_doc_type_idx'),
        ),
    ]
