# Generated by Django 6.0.4 on 2026-05-29 08:13

import re

import django.db.models.deletion
from django.db import migrations, models


def _populate_running_codes(apps, schema_editor):
    specs = (
        ("Continent", "code", "Con", 2),
        ("Country", "code", "Coun", 2),
        ("State", "code", "St", 2),
        ("City", "code", "Ci", 2),
        ("Tax", "code", "Tx", 2),
        ("Currency", "code", "Cur", 2),
        ("Company", "code", "COMP", 3),
    )

    for model_name, field_name, prefix, width in specs:
        model = apps.get_model("common_master", model_name)
        current_max = 0

        for value in model.objects.exclude(**{f"{field_name}__isnull": True}).values_list(field_name, flat=True):
            text = str(value or "")
            if not text.startswith(prefix):
                continue
            match = re.search(r"(\d+)$", text)
            if match:
                current_max = max(current_max, int(match.group(1)))

        for instance in model.objects.order_by("id"):
            existing_value = getattr(instance, field_name, None)
            if existing_value:
                continue

            current_max += 1
            setattr(instance, field_name, f"{prefix}{current_max:0{width}d}")
            instance.save(update_fields=[field_name])


class Migration(migrations.Migration):

    dependencies = [
        ('common_master', '0002_currency_customer_customeraddress_customerbankdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_countries', to='common_master.currency'),
        ),
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['code'], name='cm_city_code_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['currency', 'status'], name='cm_country_curr_st_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['code'], name='cm_state_code_idx'),
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['code'], name='cm_tax_code_idx'),
        ),
        migrations.RunPython(_populate_running_codes, migrations.RunPython.noop),
    ]
