# Generated by Django 6.0.4 on 2026-04-28 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases_Inwards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='moved_to_qcr_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='moved_to_qcr_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='process_status',
            field=models.CharField(default='GRN Process', max_length=100),
        ),
        migrations.CreateModel(
            name='QCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_reference_no', models.CharField(db_index=True, max_length=100)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(default='Active', max_length=100)),
                ('moved_to_qcr_at', models.DateTimeField()),
                ('moved_to_qcr_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_grn', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qcr_record', to='Purchases_Inwards.grn')),
            ],
        ),
    ]
