# Generated by Django 6.0.4 on 2026-05-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases_Inwards', '0005_grn_workflow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
