# Generated by Django 6.0.4 on 2026-06-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases_Inwards', '0007_qcr_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='grn_pending_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='grn',
            name='process_status',
            field=models.CharField(default='Gate Entry', max_length=100),
        ),
    ]
