# Generated by Django 6.0.4 on 2026-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Purchases_Inwards", "0008_grn_grn_pending_items_alter_grn_process_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="qcr",
            name="qcr_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qcr",
            name="qcr_completed_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="qcr",
            name="qcr_items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
