# Generated by Codex on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Purchases_Inwards", "0009_qcr_completion_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="qcr",
            name="generated_grn_no",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
