# Generated by Django 6.0.4 on 2026-04-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True)),
                ('stage', models.CharField(max_length=50)),
                ('sale_type', models.CharField(max_length=50)),
                ('sale_category', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('version_no', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('lead_source', models.CharField(max_length=100)),
                ('sale_contact', models.CharField(max_length=100)),
                ('gp_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gp_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_of_business', models.CharField(max_length=100)),
                ('sub_segment', models.CharField(max_length=100)),
                ('segment_keyword', models.CharField(blank=True, max_length=255)),
                ('required_date', models.DateField(null=True)),
                ('request_person_id', models.IntegerField(null=True)),
                ('request_department', models.CharField(blank=True, max_length=100)),
                ('required_time_start', models.TimeField(null=True)),
                ('required_time_end', models.TimeField(null=True)),
                ('required_reason', models.CharField(blank=True, max_length=255)),
                ('internal_ref_id', models.IntegerField(null=True)),
                ('invoice_ref_id', models.IntegerField(null=True)),
                ('tolerance', models.CharField(blank=True, max_length=50)),
                ('profile_type', models.CharField(blank=True, max_length=100)),
                ('capex', models.CharField(blank=True, max_length=100)),
                ('tl_code', models.CharField(blank=True, max_length=50)),
                ('delivery_challan_type', models.CharField(blank=True, max_length=100)),
                ('indent_number', models.CharField(blank=True, max_length=100)),
                ('indent_date', models.DateTimeField(null=True)),
                ('indent_receiving_datetime', models.DateTimeField(null=True)),
                ('movement_description', models.TextField(blank=True)),
                ('customer_po', models.CharField(blank=True, max_length=100)),
                ('customer_po_date', models.DateField(null=True)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('document_contact', models.TextField(blank=True)),
                ('previous_document_contact', models.TextField(blank=True)),
                ('base_order_id', models.IntegerField(null=True)),
                ('base_customer_id', models.IntegerField(null=True)),
                ('base_customer_name', models.CharField(blank=True, max_length=255)),
                ('base_order_date', models.DateTimeField(null=True)),
                ('activity_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
