# Generated by Django 6.0.4 on 2026-05-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(choices=[('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Customer', 'Customer'), ('Supplier', 'Supplier'), ('Dealer', 'Dealer'), ('Distributor', 'Distributor'), ('Shipper', 'Shipper'), ('Service Provider', 'Service Provider')], max_length=32)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('lead_source', models.CharField(blank=True, max_length=150)),
                ('market_segment', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['phone'], name='contacts_phone_idx'), models.Index(fields=['name'], name='contacts_name_idx'), models.Index(fields=['category'], name='contacts_category_idx')],
            },
        ),
    ]
