# Generated by Django 6.0.4 on 2026-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_add_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lead_source',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='market_segment',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
