# Generated by Django 6.0.4 on 2026-04-24 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('grn_no', models.CharField(max_length=100, unique=True)),
                ('grn_date', models.DateField()),
                ('supplier_invoice_no', models.CharField(max_length=100)),
                ('supplier_invoice_date', models.DateField(blank=True, null=True)),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_after_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accepted_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejected_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_item_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Purchases_Iwards.grn')),
            ],
        ),
        migrations.AddField(
            model_name='grn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchases_Iwards.supplier'),
        ),
    ]
