# Generated by Django 6.0.4 on 2026-05-05 12:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0002_item_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_store_stock_requests', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stock_requests', to='Items.item')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_store_stock_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'indexes': [models.Index(fields=['item', 'status'], name='store_request_item_status_idx'), models.Index(fields=['requested_at'], name='store_request_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', Decimal('0.001'))), name='store_request_quantity_gt_zero')],
            },
        ),
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_stock', to='Items.item')),
            ],
            options={
                'ordering': ['item_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', Decimal('0.000'))), name='store_stock_quantity_gte_zero')],
            },
        ),
        migrations.CreateModel(
            name='StoreTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('GRN_IN', 'GRN In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('reference_id', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_transactions', to='Items.item')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['item', 'transaction_type'], name='store_tx_item_type_idx'), models.Index(fields=['reference_id'], name='store_tx_reference_idx'), models.Index(fields=['created_at'], name='store_tx_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', Decimal('0.001'))), name='store_tx_quantity_gt_zero'), models.UniqueConstraint(fields=('transaction_type', 'reference_id'), name='store_tx_type_reference_unique')],
            },
        ),
    ]
