# Generated by Django 6.0.4 on 2026-05-09 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_merge_20260509_0001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='request_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ADDITIVE', 'Additive')], db_index=True, default='GENERAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['request_type', 'department'], name='store_request_type_dept_idx'),
        ),
    ]
