# Generated by Django 6.0.4 on 2026-05-12 05:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_item_external_item_id'),
        ('store', '0005_alter_stockrequest_request_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(max_length=50)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inward_entries', to='Items.item')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['item', 'date'], name='store_store_item_id_fe2f77_idx'), models.Index(fields=['reference_number'], name='store_store_referen_46e831_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0.000'))), name='store_inward_quantity_gt_zero')],
            },
        ),
        migrations.CreateModel(
            name='StoreOutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(max_length=50)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_outward_entries', to='Items.item')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
                'indexes': [models.Index(fields=['item', 'date'], name='store_store_item_id_485f24_idx'), models.Index(fields=['reference_number'], name='store_store_referen_8e2688_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0.000'))), name='store_outward_quantity_gt_zero')],
            },
        ),
    ]
