# Generated by Django 6.0.4 on 2026-05-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_storeinward_storeoutward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('STORE', 'Store'), ('BLENDING', 'Blending'), ('GENERAL', 'General'), ('QC_PENDING', 'QC Pending'), ('REJECTED', 'Rejected')], db_index=True, default='GENERAL', max_length=20),
        ),
    ]
