# Generated by Django 6.0.4 on 2026-05-26 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_warehouse_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='request_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='require_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='require_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
