# Generated by Django 6.0.4 on 2026-06-13 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_legacy_pending_requests_to_head_approval(apps, schema_editor):
    StockRequest = apps.get_model("store", "StockRequest")
    StockRequest.objects.filter(status="PENDING").update(status="PENDING_HEAD_APPROVAL")


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_stockrequest_request_date_stockrequest_require_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='head_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='head_action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_reviewed_stock_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='head_approval_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_HEAD_APPROVAL', 'Pending Blending Head Approval'), ('PENDING_STORE_ISSUE', 'Pending Store Issue'), ('HEAD_REJECTED', 'Rejected by Blending Head'), ('APPROVED', 'Fully Issued'), ('PARTIALLY_APPROVED', 'Partially Issued'), ('REJECTED', 'Rejected by Store'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_HEAD_APPROVAL', max_length=25),
        ),
        migrations.RunPython(move_legacy_pending_requests_to_head_approval, migrations.RunPython.noop),
    ]
