# Generated by Django 6.0.4 on 2026-06-03 10:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0003_item_external_item_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionInventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('ADDITIVE_WORK_CENTER', 'Additive Work Center'), ('BLEND_WIP', 'Blend WIP'), ('BLENDING_WORK_CENTER', 'Blending Work Center'), ('GRAN_TOOL_SCAN', 'Gran Tool Scan'), ('GRANULATION_WIP', 'Granulation WIP'), ('GRANULATION_WORK_CENTER', 'Granulation Work Center'), ('CONNECTION_TO_LINE', 'Connection to Line'), ('LINE_WORK_CENTER', 'Line Work Center'), ('DISCONNECTION_FROM_LINE', 'Disconnection from Line')], db_index=True, max_length=30)),
                ('batch_code', models.CharField(db_index=True, max_length=100)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('inward_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('outward_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('balance_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('from_stage', models.CharField(blank=True, max_length=30)),
                ('to_stage', models.CharField(blank=True, max_length=30)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('scan_code', models.CharField(blank=True, max_length=200, null=True)),
                ('work_center', models.CharField(blank=True, max_length=200, null=True)),
                ('line', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_inventory_transactions', to='Items.item')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
