# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_productioninventorytransaction_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productioninventorytransaction",
            name="stage",
            field=models.CharField(
                choices=[
                    ("ADDITIVE_WORK_CENTER", "Additive Work Center"),
                    ("BLEND_WIP", "Blend WIP"),
                    ("BLENDING_WORK_CENTER", "Blending Work Center"),
                    ("BLEND_STORE", "Blend Store"),
                    ("GRAN_TOOL_SCAN", "Gran Tool Scan"),
                    ("GRANULATION_WIP", "Granulation WIP"),
                    ("GRANULATION_WORK_CENTER", "Granulation Work Center"),
                    ("GRANULATION_STORE", "Granulation Store"),
                    ("CONNECTION_TO_LINE", "Connection to Line"),
                    ("LINE_WORK_CENTER", "Line Work Center"),
                    ("SCRAP_WAREHOUSE", "Scrap Warehouse"),
                    ("DISCONNECTION_FROM_LINE", "Disconnection from Line"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
