# Generated by Django 6.0.4 on 2026-05-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0002_alter_mainscreen_options_alter_role_options_and_more'),
        ('wpe_masters', '0003_wpe_role_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPEUserScreenPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_all', models.BooleanField(default=False)),
                ('view_self', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_duplicate', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('generate_invoice_access', models.BooleanField(default=False)),
                ('invoice_access', models.BooleanField(default=False)),
                ('access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WPE User Screen Permission',
                'verbose_name_plural': 'WPE User Screen Permissions',
                'db_table': 'wpe_user_screen_permission',
                'ordering': ['user_screen__main_screen__order_no', 'user_screen__order_no'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='wperolepermission',
            name='unique_role_main_screen',
        ),
        migrations.AlterUniqueTogether(
            name='wperolepermission',
            unique_together={('role', 'main_screen')},
        ),
        migrations.AddField(
            model_name='wpeuserscreenpermission',
            name='user_screen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wpe_permissions', to='admin_master.userscreen'),
        ),
    ]
