# Generated by Django 6.0.4 on 2026-05-21 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpe_masters', '0004_wpe_user_screen_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_collation='utf8mb4_bin', db_index=True, max_length=200)),
                ('code', models.CharField(db_index=True, editable=False, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Product Type Category',
                'verbose_name_plural': 'Product Type Categories',
                'db_table': 'wpe_product_type_category',
                'ordering': ['sort_order', 'name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='wpe_pt_cat_active_sort_idx'), models.Index(fields=['sort_order', 'name'], name='wpe_pt_cat_sort_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='wpe_pt_category_name_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ProductTypeSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_collation='utf8mb4_bin', db_index=True, max_length=200)),
                ('code', models.CharField(db_index=True, editable=False, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='wpe_masters.producttypecategory')),
            ],
            options={
                'verbose_name': 'Product Type Subtype',
                'verbose_name_plural': 'Product Type Subtypes',
                'db_table': 'wpe_product_type_subtype',
                'ordering': ['category__sort_order', 'category__name', 'sort_order', 'name', 'id'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='wpe_pt_subtype_cat_active_idx'), models.Index(fields=['category', 'sort_order'], name='wpe_pt_subtype_cat_sort_idx'), models.Index(fields=['sort_order', 'name'], name='wpe_pt_subtype_sort_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='wpe_pt_subtype_category_name_uniq')],
            },
        ),
    ]
