from django.db import migrations
from django.utils.text import slugify


PRODUCT_TYPE_SEED_DATA = [
    ("Blend", ["WPE", "Lumber"]),
    (
        "Blending",
        [
            "General",
            "LDPE",
            "Master batch",
            "Wood Powder",
            "Rice Husk Powder",
            "Coupling Agent",
            "CaCo3",
            "Glass Fiber",
            "Antioxidant Agent",
            "UV Agent",
            "Lubricant",
            "Pigment",
            "Masterbatch",
            "PE Wax",
            "PE",
            "Stearic Acid",
            "ETP",
            "HDPE Chips",
            "HDPE Granuals",
        ],
    ),
    (
        "Chemicals",
        [
            "Adhesive",
            "Cleaner",
            "Water Treatment Chemical",
            "Cleaning Agent",
            "Paints & Coatings",
            "Paints Accessories",
            "Paint Tools",
            "Solvent",
            "Chemicals",
            "Paint/Stainer",
            "Thinner",
            "Paint",
            "Sealant",
            "Rust Protection",
            "Absorbent",
        ],
    ),
    (
        "Cleaning and Hygiene",
        [
            "Cleaning Tools",
            "Cleaning Agents",
            "Sanitizers and Sprays",
            "Cleaner",
            "Freshener",
            "Dustbins and Covers",
            "Equipment",
            "Cleaning Tool",
            "Tape",
        ],
    ),
    ("Computer Accessories", ["Desktop", "Power Supply", "Desktop PC"]),
    ("Devices", ["Printer", "Scanner"]),
    (
        "Electrical",
        [
            "Pest Control",
            "Audio Equipment",
            "Thermocouple Wire",
            "Wire",
            "Socket",
            "Flexible Cable",
            "Solenoid Coil",
            "Fuse Wire",
            "Armoured Cable",
            "Fuse",
            "TPN Switch",
            "Contactor",
            "Cable Gland",
            "Starter",
            "Plug",
            "Industrial Plug",
            "Heater Cable",
            "Switch",
            "Enclosure Box",
            "Distribution Box",
            "SPN Distribution",
            "Switch with Enclosure",
            "Relay",
            "Sensor",
            "Safety",
            "Spiral Hose",
            "Siren",
            "Indicator Lamp",
            "Switching",
            "Insulator",
            "Coil",
            "Controller",
            "Wiring Accessories",
            "Hand Tools",
            "Power Cable",
            "Safety Equipment",
            "Power Backup",
            "Control Panel",
            "Wiring",
            "Connectors",
            "Lighting",
            "Cable Accessories",
            "Power Tools",
            "Power Tools Accessories",
            "Switch Enclosure",
            "ELCB",
            "Power Supply",
            "Protection Devices",
            "Meter",
            "Sensor/Controller",
            "Motor Drive",
            "Cable",
            "Limit Switch",
            "UPS",
            "Alarm",
            "Enclosure",
            "Junction Box",
            "Socket & Plug",
            "Protection Device",
            "Terminal",
            "Hand Tool",
            "Thermal Paste",
            "Service Charge",
            "Light Fixture",
            "MCB",
            "Fiber Optic Accessories",
            "Socket & Switch",
            "Sensor Wire",
            "Sensor Cable",
            "Insulation Sleeve",
            "Timer",
            "Transformer Accessory",
            "Battery",
            "Tie",
            "Service",
            "MCCB",
            "Drive",
            "Sleeve",
            "Plug & Socket",
            "Clamp Meter",
            "Copper Socket",
            "Gland",
            "General",
        ],
    ),
    (
        "Fastener",
        [
            "Hex Bolt",
            "Allen Bolt",
            "Fasteners",
            "Pin",
            "Nut",
            "Washer",
            "Clamp",
            "Fastener",
            "Screw",
            "Bolt",
            "Oil Seal",
            "Bolt & Nut",
            "Seal",
            "Fas",
        ],
    ),
    ("Furniture and Fixtures", ["Equipment", "Storage", "Table", "Chair", "Stand"]),
    (
        "General",
        [
            "Bucket",
            "Food",
            "Landscaping Service",
            "Brush",
            "SIM Sheet",
            "Tray",
            "Hinge",
            "Door",
            "Aluminium Tube",
            "Road Safety Equipment",
            "Pipe",
            "Door Accessories",
            "Sheet",
            "Structural Angle",
            "Accessories",
            "Structural Accessories",
            "Structural Tube",
            "Plate",
            "Material",
            "Angle",
            "Channel",
            "Sample Box",
            "Printer Consumable",
            "Tester",
            "Ink",
            "Others",
        ],
    ),
    (
        "Instrumentation",
        [
            "Equipment",
            "Potentiometer",
            "Ammeter",
            "Current Transformer",
            "Digital Ammeter",
            "Pressure Gauge",
            "Temperature Gauge",
            "Temperature Measurement",
            "Weighing",
            "Glassware",
            "Weighing Sensor",
            "Tester",
            "Testing Accessories",
            "Meter",
            "Tray",
            "Glassware/Plasticware",
            "Timer",
            "Testing",
            "Tool",
            "Testing Tool",
            "Gauge",
            "Calibration Kit",
            "Filter",
            "Measuring Tool",
            "Water",
            "Testing Instrument",
            "Manifold",
            "Temperature Controller",
            "Vacuum Gauge",
            "Flow Meter",
        ],
    ),
    (
        "Kitchen and Dining",
        [
            "Ointment",
            "Cream",
            "Tablet",
            "Plaster",
            "Gel",
            "Spray",
            "Miscellaneous",
            "Water and Beverage Containers",
            "Serving and Cookware",
            "Food Storage",
        ],
    ),
    ("Lamp", ["LED Street Light", "Tube Light", "General Purpose", "Indicator", "Panel Light"]),
    (
        "Lubricants",
        ["FRL Unit Oil", "Grease", "Industrial Oil", "Compressor Oil", "Gear Oil", "Accessories", "Hand Tools", "Oil"],
    ),
    ("LUMBER", ["Master batch", "PE wax", "Stearic Acid"]),
    (
        "Maintenance Consumables",
        [
            "Wire Tag",
            "Gas",
            "Electrical Paste",
            "Electrical Tape",
            "Paste",
            "Tape",
            "Lubricant",
            "Welding",
            "Installation",
            "Record",
            "General",
        ],
    ),
    ("MSB", ["Four Pole", "Single Pole", "Two Pole", "Three Pole", "Siemens MPCB"]),
    (
        "Mechanical",
        [
            "Equipment",
            "Cover",
            "Bag",
            "Blower Fan",
            "Butterfly Valve",
            "Hose Clamp",
            "Heater",
            "Pipe Clamp",
            "Solenoid Valve",
            "Spare",
            "Bearing",
            "Bearing Accessory",
            "Roller",
            "Lock",
            "Crusher Blade",
            "Shaft",
            "Machine Part",
            "Heater Sleeve",
            "Coupling",
            "Oil Seal",
            "Water Filter",
            "Pump",
            "Mesh Filter",
            "Seal",
            "Measuring Tools",
            "Testing Equipment",
            "Machine Components",
            "Plastic Processing",
            "Air Compressor",
            "Air System Accessories",
            "Cooling Equipment",
            "Dust Collection",
            "Trolleys",
            "Storage",
            "Cleaning",
            "Metalworking",
            "Hand Tools",
            "Tool Storage",
            "Power Tools",
            "Cutting Accessories",
            "Sealing",
            "Trolley Wheel",
            "Magnetic Tool",
            "Trolley",
            "Belt",
            "Plastic Processing Accessories",
            "Heating Equipment",
            "Drum",
            "Motor",
            "Fan",
            "Sensor",
            "PLC",
            "Blower",
            "Gearbox",
            "Motor with Gearbox",
            "Hydraulic Tool",
            "Plastic Accessories",
            "Flange",
            "Clamp",
            "Cutting Tool",
            "Gasket",
            "Welding Machine",
            "Fasteners",
            "Container",
            "Cutting Machine",
            "Bin Cover",
            "Bin",
            "Filter",
            "Trolley Accessory",
            "Drilling Machine",
            "Fastener",
            "Mold Accessory",
            "Tray",
            "Motor Accessories",
            "Hose",
            "Mixer Accessories",
            "Extrusion Component",
            "Granulation Machine",
            "Die",
            "Embossing Machine",
            "Mixer",
            "Abrasive",
            "Screw Barrel",
            "Mixer Accessory",
            "Blade",
            "Cutter Accessory",
            "Component",
            "Gearbox Assembly",
            "Process",
            "Pin",
            "Bush",
            "Net",
            "Screw Segment",
            "Rack",
            "Accessory",
            "Wheel",
            "Barrel",
            "Compressor",
            "Safety Guard",
            "Motor Flange",
            "Mesh",
            "Sheet",
            "Propeller",
            "Grinder",
            "Pipe",
            "Vacuum Pump",
            "Sprocket",
            "Cutter Bush",
            "Loader",
            "Cooling Fan",
            "Gear Box",
            "Exhaust Bellow",
            "General",
        ],
    ),
    ("Miscellaneous", ["Paper and Waste", "Container", "Sheet", "Wire Mesh"]),
    (
        "Office Suppliers",
        [
            "Files and Paper",
            "Writing and Marking Tools",
            "Cutting and Measuring Tools",
            "Binding and Punching Tools",
            "Clock Accessories",
            "Stationery",
            "Cleaning",
            "Cover",
            "Sticker",
            "Notebook",
            "Board",
            "Box",
            "Notice Board",
            "Tape",
            "Checklist",
            "Log Sheet",
            "Laminating Sheet",
            "Report Sheet",
            "Holder",
            "Brochure",
            "ID Accessory",
            "Battery",
            "Adapter",
            "Catalogue",
            "File",
            "Log Book",
            "Ink",
            "Report",
            "Planner",
            "Book",
            "Connector",
            "Utensils",
        ],
    ),
    (
        "Packaging",
        [
            "Tapes",
            "Bags",
            "Films",
            "Labels",
            "Carbon Sheets",
            "Corrugate Sheets",
            "Miscellaneous",
            "Tape",
            "Foam Sheet",
            "Insulation Sheet",
            "Sheet",
            "Bag",
        ],
    ),
    (
        "Piping",
        [
            "Hose Collar",
            "Nipple",
            "Hose Connector",
            "Tee",
            "Coupling",
            "Dummy Plug",
            "Elbow",
            "Bush",
            "Valve",
            "Barrel Nipple",
            "PPR Pipe",
            "PVC Pipe",
            "PVC Elbow",
            "PVC Fitting",
            "Ball Valve",
            "Shoe",
            "Female Threaded Adapter",
            "Male Threaded Adapter",
            "UPVC Pipe",
            "Tank Connector",
            "Flexible Hose",
            "Gasket",
            "Industrial Hose",
            "Non-Return Valve (NRV)",
            "Union",
            "Reducer",
            "Bellow Hose",
            "Flange",
            "Tank",
            "Pipe Fittings",
            "Pipe Accessories",
            "Tap",
            "Pipe Fitting",
            "Hose",
            "Bend",
            "MTA",
            "Pipe",
            "Foot Valve",
            "Clamp",
            "Hose Accessory",
            "Brush",
            "Tube",
            "Connector",
            "Clip",
            "Saddle",
            "Cap",
            "Tape",
            "Solenoid Valve",
            "SS Valve",
            "UPVC Reducer",
            "Hex Nipple",
            "MS Valve",
            "UPVC Flange",
        ],
    ),
    (
        "Pneumatic",
        [
            "Air Connector",
            "Air Fitting",
            "Flow Control Valve",
            "Air Hose",
            "Union",
            "Union Tee",
            "Filter-Regulator-Lubricator",
            "Fittings",
            "Hose",
            "Cylinder",
            "Regulator",
            "Valve",
            "Connector",
            "Gun",
            "Grinder",
            "Air Valve",
        ],
    ),
    ("Production", ["General"]),
    ("Recycling", ["General", "Bag", "Items"]),
    (
        "Safety and PPE",
        [
            "Miscellaneous Safety",
            "Head and Face Protection",
            "Body Protection",
            "Gloves",
            "Storage",
            "Safety Shoes",
            "Hand Protection",
            "Umbrella",
            "Lockout/Tagout",
        ],
    ),
    ("Scrap", ["General", "Tooling Scrap", "Production Scrap", "Blending Scrap", "Quality Scrap", "Downtime Scrap"]),
    ("Staff Uniform and Accessories", ["Uniform", "Footwear"]),
    (
        "Tools",
        [
            "Spanner",
            "Grinding Wheel",
            "Allen Key",
            "Screwdriver",
            "Brushing Roller",
            "Timer",
            "Diagnostic Tool",
            "Emery Sheet",
            "Hand Tool",
            "Measuring Tool",
            "Hand Tool Accessory",
            "Cutting Accessories",
            "Hand Tool Set",
            "Abrasive",
            "Pneumatic Tool",
            "Cutting Tool",
            "Chisel",
            "Electrical Tester",
            "Machine",
            "Drill Accessory",
            "Cutter",
            "Roller",
            "Clamp",
            "Grinder",
            "Hacksaw",
            "Snipper",
            "Hammer",
            "Drill Bit",
            "Wrench",
            "Saw Blade",
            "Steel Rule",
            "Charger Gun",
            "Flame Gun",
            "Hand Tools",
        ],
    ),
    (
        "WPE",
        [
            "Wood Powder",
            "Crumps",
            "Coupling agent",
            "Calcium carbonate",
            "Antioxidant Agent",
            "UV agent",
            "Lubricant",
            "Pigment",
            "Chips",
        ],
    ),
    ("Decking", ["Primedeck", "Enduradeck", "Elite Deck", "Elite Deck - B", "Elite Deck - A"]),
    ("Railing", ["Rail Post", "Horizontal Rail", "Baluster"]),
    ("Auxilary", ["Joist Profile", "Elite Angle", "Fine Angle", "Track Angle", "Outer Corner Trim"]),
    ("Edge", ["Prime Edge", "Elite Plank"]),
    ("Cladding", ["Elite Clad 6L", "Elite Clad %L", "Elite CLad 4L", "Elite CLad - Flat"]),
    ("Lumber", ["Lumber-01", "Lumber-02", "Lumber-03"]),
    ("WPE Sample Box & Catalogue", ["General"]),
    ("WPE Accessories", ["General"]),
    ("Hardware", ["General"]),
    ("Strickers", ["General"]),
]


def build_unique_code(model_cls, source_value: str, existing_codes: set[str], prefix: str) -> str:
    base = slugify(source_value or "")[:120].strip("-") or prefix
    candidate = base
    counter = 2

    while candidate in existing_codes or model_cls.objects.filter(code=candidate).exists():
        suffix = f"-{counter}"
        trimmed_base = base[: 120 - len(suffix)]
        candidate = f"{trimmed_base}{suffix}"
        counter += 1

    existing_codes.add(candidate)
    return candidate


def seed_product_types(apps, schema_editor):
    ProductTypeCategory = apps.get_model("wpe_masters", "ProductTypeCategory")
    ProductTypeSubtype = apps.get_model("wpe_masters", "ProductTypeSubtype")
    MainScreen = apps.get_model("admin_master", "MainScreen")
    ScreenSection = apps.get_model("admin_master", "ScreenSection")
    UserScreen = apps.get_model("admin_master", "UserScreen")

    used_category_codes = set(ProductTypeCategory.objects.values_list("code", flat=True))
    used_subtype_codes = set(ProductTypeSubtype.objects.values_list("code", flat=True))

    for category_index, (category_name, subtype_names) in enumerate(PRODUCT_TYPE_SEED_DATA, start=1):
        category_name = category_name.strip()
        category_defaults = {
            "code": build_unique_code(
                ProductTypeCategory,
                category_name,
                used_category_codes,
                prefix="product-type-category",
            ),
            "description": "",
            "sort_order": category_index * 10,
            "is_active": True,
        }
        category, created = ProductTypeCategory.objects.get_or_create(
            name=category_name,
            defaults=category_defaults,
        )
        if not created:
            update_fields = []
            if not getattr(category, "code", None):
                category.code = build_unique_code(
                    ProductTypeCategory,
                    category_name,
                    used_category_codes,
                    prefix="product-type-category",
                )
                update_fields.append("code")
            if category.sort_order != category_defaults["sort_order"]:
                category.sort_order = category_defaults["sort_order"]
                update_fields.append("sort_order")
            if not category.is_active:
                category.is_active = True
                update_fields.append("is_active")
            if update_fields:
                category.save(update_fields=update_fields)

        seen_exact_subtypes = set()
        for subtype_index, subtype_name in enumerate(subtype_names, start=1):
            subtype_name = subtype_name.strip()
            if not subtype_name or subtype_name in seen_exact_subtypes:
                continue
            seen_exact_subtypes.add(subtype_name)

            subtype_defaults = {
                "code": build_unique_code(
                    ProductTypeSubtype,
                    f"{category_name}-{subtype_name}",
                    used_subtype_codes,
                    prefix="product-type-subtype",
                ),
                "description": "",
                "sort_order": subtype_index * 10,
                "is_active": True,
            }
            subtype, created = ProductTypeSubtype.objects.get_or_create(
                category=category,
                name=subtype_name,
                defaults=subtype_defaults,
            )
            if not created:
                update_fields = []
                if not getattr(subtype, "code", None):
                    subtype.code = build_unique_code(
                        ProductTypeSubtype,
                        f"{category_name}-{subtype_name}",
                        used_subtype_codes,
                        prefix="product-type-subtype",
                    )
                    update_fields.append("code")
                if subtype.sort_order != subtype_defaults["sort_order"]:
                    subtype.sort_order = subtype_defaults["sort_order"]
                    update_fields.append("sort_order")
                if not subtype.is_active:
                    subtype.is_active = True
                    update_fields.append("is_active")
                if update_fields:
                    subtype.save(update_fields=update_fields)

    masters_screen, _ = MainScreen.objects.get_or_create(
        name="Masters",
        defaults={"code": "masters", "order_no": 1, "status": True},
    )
    if not masters_screen.code:
        masters_screen.code = "masters"
        masters_screen.save(update_fields=["code"])

    wpe_section, _ = ScreenSection.objects.get_or_create(
        main_screen=masters_screen,
        name="WPE Masters",
        defaults={
            "code": "wpe-masters",
            "order_no": 4,
            "is_active": True,
            "description": "Governed WPE-specific master data.",
        },
    )

    UserScreen.objects.update_or_create(
        code="wpe-product-type-master",
        defaults={
            "main_screen": masters_screen,
            "screen_section": wpe_section,
            "screen_name": "Product Types Master",
            "folder_name": "wpe-product-type-master",
            "order_no": 1,
            "icon": "Layers",
            "description": "Controls Product Type category and subtype governance.",
            "is_active": True,
            "available_actions": ["add", "update", "list", "delete", "view"],
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("admin_master", "0002_alter_mainscreen_options_alter_role_options_and_more"),
        ("wpe_masters", "0005_producttypecategory_producttypesubtype"),
    ]

    operations = [
        migrations.RunPython(seed_product_types, migrations.RunPython.noop),
    ]
