# Generated by Django 6.0.4 on 2026-05-29 11:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


def _next_code(existing_codes, prefix: str, width: int, counter: int) -> str:
    while True:
        candidate = f"{prefix}{counter:0{width}d}"
        if candidate not in existing_codes:
            existing_codes.add(candidate)
            return candidate
        counter += 1


def backfill_master_codes(apps, schema_editor):
    WarehouseMaster = apps.get_model("wpe_masters", "WarehouseMaster")
    DepartmentMaster = apps.get_model("wpe_masters", "DepartmentMaster")
    RoleMaster = apps.get_model("wpe_masters", "RoleMaster")

    for model_cls, prefix, width in (
        (WarehouseMaster, "WH", 3),
        (DepartmentMaster, "DEPT", 3),
        (RoleMaster, "ROLE", 3),
    ):
        existing_codes = set(
            filter(
                None,
                model_cls.objects.exclude(code__isnull=True).exclude(code="").values_list("code", flat=True),
            )
        )
        counter = 1
        for instance in model_cls.objects.filter(code__isnull=True).order_by("id"):
            instance.code = _next_code(existing_codes, prefix, width, counter)
            instance.save(update_fields=["code"])
            counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('wpe_masters', '0006_seed_product_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Store Master',
                'verbose_name_plural': 'Store Masters',
                'db_table': 'wpe_store_master',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uom_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('decimal_allowed', models.BooleanField(default=False)),
                ('decimal_places', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit Master',
                'verbose_name_plural': 'Unit Masters',
                'db_table': 'wpe_unit_master',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='departmentmaster',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='departmentmaster',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='wpe_masters.wpeusercreation'),
        ),
        migrations.AddField(
            model_name='departmentmaster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehousemaster',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='warehousemaster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehousemaster',
            name='warehouse_type',
            field=models.CharField(choices=[('FG', 'FG'), ('RM', 'RM'), ('SCRAP', 'Scrap')], default='RM', max_length=10),
        ),
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designations', to='wpe_masters.departmentmaster')),
            ],
            options={
                'verbose_name': 'Designation Master',
                'verbose_name_plural': 'Designation Masters',
                'db_table': 'wpe_designation_master',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='wpe_masters.designationmaster'),
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_code', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('item_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('item_type', models.CharField(choices=[('RM', 'RM'), ('ADDITIVE', 'Additive'), ('PACKING', 'Packing'), ('FG', 'FG')], db_index=True, default='RM', max_length=12)),
                ('hsn_code', models.CharField(blank=True, max_length=50)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('maximum_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='wpe_masters.producttypesubtype')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='wpe_masters.unitmaster')),
            ],
            options={
                'verbose_name': 'Item Master',
                'verbose_name_plural': 'Item Masters',
                'db_table': 'wpe_item_master',
                'ordering': ['item_name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='designationmaster',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='wpe_designation_department_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['sub_category', 'is_active'], name='wpe_item_subcat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmaster',
            index=models.Index(fields=['item_type', 'is_active'], name='wpe_item_type_active_idx'),
        ),
        migrations.RunPython(backfill_master_codes, migrations.RunPython.noop),
    ]
