# Generated by Django 6.0.4 on 2026-05-29 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_bomvariant_access_password_hash'),
        ('wpe_masters', '0007_storemaster_unitmaster_departmentmaster_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialPortConfigurationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('port_name', models.CharField(blank=True, default='/dev/ttyS1', max_length=100)),
                ('baud_rate', models.PositiveIntegerField(default=9600)),
                ('parity', models.CharField(choices=[('NONE', 'None')], default='NONE', max_length=20)),
                ('data_bits', models.PositiveSmallIntegerField(default=8)),
                ('stop_bits', models.PositiveSmallIntegerField(default=1)),
                ('timeout', models.PositiveIntegerField(blank=True, null=True)),
                ('read_format', models.CharField(choices=[('ASCII', 'ASCII'), ('HEX', 'HEX')], default='ASCII', max_length=20)),
            ],
            options={
                'verbose_name': 'Serial Port Configuration Master',
                'verbose_name_plural': 'Serial Port Configuration Masters',
                'db_table': 'wpe_serial_port_configuration_master',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrinterMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('printer_type', models.CharField(choices=[('BARCODE', 'Barcode'), ('QR', 'QR'), ('STICKER', 'Sticker')], max_length=20)),
                ('connection_type', models.CharField(choices=[('USB', 'USB'), ('NETWORK', 'Network')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('paper_size', models.CharField(default='LABEL', max_length=40)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='wpe_masters.departmentmaster')),
            ],
            options={
                'verbose_name': 'Printer Master',
                'verbose_name_plural': 'Printer Masters',
                'db_table': 'wpe_printer_master',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QRLabelTemplateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('label_type', models.CharField(choices=[('BIN', 'Bin'), ('BAG', 'Bag'), ('PRODUCT', 'Product'), ('REGRIND', 'Regrind')], max_length=20)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qr_data_format', models.CharField(choices=[('JSON', 'JSON'), ('TEXT', 'Text')], default='JSON', max_length=20)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_label_templates', to='wpe_masters.printermaster')),
            ],
            options={
                'verbose_name': 'QR Label Template Master',
                'verbose_name_plural': 'QR Label Template Masters',
                'db_table': 'wpe_qr_label_template_master',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeighmentScaleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('connection_type', models.CharField(choices=[('SERIAL', 'Serial'), ('USB', 'USB'), ('API', 'API')], default='SERIAL', max_length=20)),
                ('port_name', models.CharField(blank=True, default='COM1', max_length=50)),
                ('baud_rate', models.PositiveIntegerField(default=9600)),
                ('data_bits', models.PositiveSmallIntegerField(default=8)),
                ('parity', models.CharField(choices=[('NONE', 'None')], default='NONE', max_length=20)),
                ('stop_bits', models.PositiveSmallIntegerField(default=1)),
                ('is_auto_capture', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weighment_scales', to='wpe_masters.departmentmaster')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weighment_scales', to='production.productionmachine')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weighment_scales', to='wpe_masters.unitmaster')),
            ],
            options={
                'verbose_name': 'Weighment Scale Master',
                'verbose_name_plural': 'Weighment Scale Masters',
                'db_table': 'wpe_weighment_scale_master',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
