# Generated by Django 6.0.4 on 2026-06-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpe_masters', '0009_ensure_blend_production_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmaster',
            options={'ordering': ['item_name', 'id'], 'verbose_name': 'Item Variant', 'verbose_name_plural': 'Item Variants'},
        ),
        migrations.AlterModelOptions(
            name='producttypesubtype',
            options={'ordering': ['category__sort_order', 'category__name', 'sort_order', 'name', 'id'], 'verbose_name': 'Item Sub Category', 'verbose_name_plural': 'Item Sub Categories'},
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
