# Generated by Django 6.0.4 on 2026-06-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpe_masters', '0010_alter_itemmaster_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttypecategory',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'Item Category', 'verbose_name_plural': 'Item Categories'},
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='itemmaster',
            constraint=models.UniqueConstraint(fields=('sub_category', 'item_name'), name='wpe_item_subcategory_name_uniq'),
        ),
    ]
