# Generated by Django 6.0.4 on 2026-06-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpe_masters', '0011_alter_producttypecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmaster',
            name='center_type',
            field=models.CharField(choices=[('GRN_CENTER', 'GRN Stock Center'), ('BLENDING_CENTER', 'Blending Stock Center'), ('WAREHOUSE_CENTER', 'Warehouse Stock Center')], db_index=True, default='BLENDING_CENTER', max_length=20),
        ),
    ]
