# Generated by Codex on 2026-07-17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wpe_masters", "0012_locationmaster_center_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapTypeMaster",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "scrap_type",
                    models.CharField(
                        choices=[
                            ("STARTUP", "Startup"),
                            ("SETUP", "Setup"),
                            ("PROCESS", "Process"),
                            ("DOWNTIME", "Downtime"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scrap Type Master",
                "verbose_name_plural": "Scrap Type Masters",
                "db_table": "wpe_scrap_type_master",
                "ordering": ["scrap_type", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="scraptypemaster",
            constraint=models.UniqueConstraint(fields=("scrap_type", "name"), name="wpe_scrap_type_name_uniq"),
        ),
    ]
