# Generated by Django 6.0.4 on 2026-05-18 11:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_id', models.CharField(db_index=True, help_text='Unique production order ID', max_length=50, unique=True)),
                ('production_type', models.CharField(choices=[('RECYCLING_PRODUCTION', 'Recycling Production - WPE'), ('BLENDING_PRODUCTION', 'Blending Production - WPE'), ('COMPOUNDING', 'Compounding')], default='RECYCLING_PRODUCTION', max_length=50)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PLAN_COMPLETED', 'Plan Completed (Ready to Close)'), ('CLOSED', 'Closed'), ('PLANNED', 'Planned')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('batch_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('batch_date', models.DateField(blank=True, null=True)),
                ('production_date', models.DateField()),
                ('shift', models.CharField(blank=True, default='Shift 1 (6:00 am - 2:00 pm)', help_text='Production shift information', max_length=50)),
                ('plan_id', models.CharField(blank=True, help_text='Associated plan ID', max_length=100, null=True)),
                ('planned_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Planned production quantity in kgs', max_digits=14)),
                ('planned_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Planned weight in kgs', max_digits=14)),
                ('line_number', models.CharField(blank=True, help_text='Production line number', max_length=100, null=True)),
                ('line_name', models.CharField(blank=True, help_text='Production line name (e.g., Recycling)', max_length=255, null=True)),
                ('total_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total production quantity in kgs', max_digits=14)),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.000'), help_text='Other costs (overhead, utilities, etc.)', max_digits=14)),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0.000'), help_text='Total material cost', max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.000'), help_text='Total production cost', max_digits=14)),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Production start date and time')),
                ('end_date_time', models.DateTimeField(blank=True, help_text='Production end date and time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-production_date', '-created_at'],
                'indexes': [models.Index(fields=['production_id'], name='production_id_idx'), models.Index(fields=['status', 'production_date'], name='production_status_date_idx'), models.Index(fields=['production_type', 'status'], name='production_type_status_idx'), models.Index(fields=['batch_number'], name='production_batch_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_raw_material_cost', models.DecimalField(decimal_places=2, default=Decimal('0.000'), help_text='Total cost of raw materials', max_digits=14)),
                ('total_other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.000'), help_text='Total other costs (overhead, utilities, etc.)', max_digits=14)),
                ('total_production_cost', models.DecimalField(decimal_places=2, default=Decimal('0.000'), help_text='Total production cost', max_digits=14)),
                ('total_input_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total input quantity in kgs', max_digits=14)),
                ('total_output_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total output quantity in kgs', max_digits=14)),
                ('total_waste_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total waste/scrap quantity in kgs', max_digits=14)),
                ('yield_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Production yield percentage', max_digits=5)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.000'), help_text='Cost per unit of output', max_digits=14)),
                ('is_finalized', models.BooleanField(default=False, help_text='Whether the summary is finalized/locked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Production Summary',
                'verbose_name_plural': 'Production Summaries',
            },
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RAW_MATERIAL_IN', 'Raw Material In'), ('OUTPUT_IN_PRODUCTION', 'Output in Production'), ('RETURN_TO_MC', 'Send Returns to MC'), ('OUTPUT_TO_WAREHOUSE', 'Send Output to Warehouse')], db_index=True, max_length=50)),
                ('item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('source_location', models.CharField(help_text='Source location (Material Center, Production, etc.)', max_length=255)),
                ('destination_location', models.CharField(help_text='Destination location', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of material', max_digits=14)),
                ('unit', models.CharField(default='kgs', max_length=50)),
                ('warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50)),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_movements', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Material Movement',
                'verbose_name_plural': 'Material Movements',
                'ordering': ['-movement_date'],
                'indexes': [models.Index(fields=['production_order', 'movement_type'], name='material_movement_type_idx'), models.Index(fields=['movement_date'], name='material_movement_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction ID', max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward')], db_index=True, max_length=20)),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.TimeField(blank=True, null=True)),
                ('item_id', models.CharField(max_length=100)),
                ('item_number', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_in', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Inward quantity', max_digits=14)),
                ('quantity_out', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Outward quantity', max_digits=14)),
                ('unit', models.CharField(default='kgs', max_length=50)),
                ('warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_location', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.CharField(blank=True, help_text='Reference to GRN, PO, etc.', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Production Transaction',
                'verbose_name_plural': 'Production Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='transaction_id_idx'), models.Index(fields=['production_order', 'transaction_type'], name='transaction_type_idx'), models.Index(fields=['transaction_date'], name='transaction_date_idx')],
            },
        ),
    ]
