# Generated by Django 6.0.4 on 2026-05-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_item_external_item_id'),
        ('production', '0002_bom_machine_batch'),
        ('wpe_masters', '0006_seed_product_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bomvariantcomponent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bomvariantcomponent',
            name='product_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_variant_components', to='wpe_masters.producttypesubtype'),
        ),
        migrations.AlterField(
            model_name='batchweightentry',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Items.item'),
        ),
        migrations.AlterField(
            model_name='bomvariantcomponent',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Items.item'),
        ),
        migrations.AddConstraint(
            model_name='bomvariantcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('item__isnull', False), ('product_subtype__isnull', False), _connector='OR'), name='production_bom_component_source_required'),
        ),
    ]
