# Generated by Django 6.0.4 on 2026-05-29 15:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionordermaterialplan'),
        ('wpe_masters', '0007_storemaster_unitmaster_departmentmaster_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCreationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_group', models.CharField(blank=True, choices=[('DARK', 'Dark'), ('LIGHT', 'Light')], max_length=16)),
            ],
            options={
                'verbose_name': 'Color Creation',
                'verbose_name_plural': 'Color Creations',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackingTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_pcs', models.PositiveIntegerField(default=0)),
                ('standard_weight', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('uom', models.CharField(choices=[('NOS', 'Nos'), ('KG', 'KG')], max_length=16)),
            ],
            options={
                'verbose_name': 'Packing Type',
                'verbose_name_plural': 'Packing Types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileSizeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('thickness', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('length', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('uom', models.CharField(choices=[('MM', 'MM'), ('METER', 'Meter')], max_length=16)),
            ],
            options={
                'verbose_name': 'Profile Size',
                'verbose_name_plural': 'Profile Sizes',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productionmachine',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='productionmachine',
            name='capacity_uom',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('HOUR', 'Hour'), ('KG_PER_HOUR', 'KG / Hour')], max_length=20),
        ),
        migrations.AddField(
            model_name='productionmachine',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_machines', to='wpe_masters.departmentmaster'),
        ),
        migrations.AddField(
            model_name='productionmachine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='productionmachine',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productionmachine',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Maintenance'), ('BREAKDOWN', 'Breakdown')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionmachine',
            name='machine_type',
            field=models.CharField(choices=[('HIGH_SPEED_MIX', 'High Speed Mix'), ('GRANULATOR', 'Granulator'), ('BLENDING', 'Blending'), ('GRANULATION', 'Granulation'), ('EXTRUSION', 'Extrusion'), ('EXTRUDER', 'Extruder'), ('MIXER', 'Mixer')], max_length=30),
        ),
        migrations.CreateModel(
            name='BagCreationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_weight', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('uom', models.CharField(choices=[('KG', 'KG')], default='KG', max_length=16)),
                ('current_status', models.CharField(choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied'), ('USED', 'Used')], max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_bags', to='wpe_masters.departmentmaster')),
            ],
            options={
                'verbose_name': 'Bag Creation',
                'verbose_name_plural': 'Bag Creations',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinCreationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('capacity_uom', models.CharField(choices=[('KG', 'KG'), ('NOS', 'Nos')], max_length=16)),
                ('current_status', models.CharField(blank=True, choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied'), ('HOLD', 'Hold')], max_length=16)),
                ('current_material', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_bins', to='wpe_masters.departmentmaster')),
            ],
            options={
                'verbose_name': 'Bin Creation',
                'verbose_name_plural': 'Bin Creations',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackingMaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uom', models.CharField(choices=[('KG', 'KG'), ('NOS', 'Nos')], max_length=16)),
                ('standard_consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_materials', to='wpe_masters.itemmaster')),
            ],
            options={
                'verbose_name': 'Packing Material',
                'verbose_name_plural': 'Packing Materials',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionLineMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('capacity_uom', models.CharField(blank=True, choices=[('KG', 'KG'), ('HOUR', 'Hour'), ('KG_PER_HOUR', 'KG / Hour')], max_length=20)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('RUNNING', 'Running'), ('MAINTENANCE', 'Maintenance')], default='FREE', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_lines', to='wpe_masters.departmentmaster')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_lines', to='production.productionmachine')),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileCreationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('length', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight_per_piece', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('uom', models.CharField(choices=[('NOS', 'Nos'), ('METER', 'Meter')], max_length=16)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='production.colorcreationmaster')),
                ('packing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='production.packingtypemaster')),
                ('profile_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_profiles', to='wpe_masters.producttypecategory')),
                ('profile_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='production.profilesizemaster')),
            ],
            options={
                'verbose_name': 'Profile Creation',
                'verbose_name_plural': 'Profile Creations',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkCentreCreationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_centres', to='wpe_masters.departmentmaster')),
            ],
            options={
                'verbose_name': 'Work Centre Creation',
                'verbose_name_plural': 'Work Centre Creations',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
