# Generated by Django 6.0.4 on 2026-05-29 16:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_colorcreationmaster_packingtypemaster_and_more'),
        ('wpe_masters', '0007_storemaster_unitmaster_departmentmaster_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bomvariant',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomvariant',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_production_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bomvariant',
            name='batch_size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='bomvariant',
            name='batch_uom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bomvariant',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('INACTIVE', 'Inactive')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.AddField(
            model_name='bomvariantcomponent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name='BOMCreationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_version', models.CharField(blank=True, max_length=30)),
                ('output_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('output_uom', models.CharField(blank=True, choices=[('NOS', 'Nos'), ('KG', 'KG')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=16)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_creations', to='production.profilecreationmaster')),
            ],
            options={
                'verbose_name': 'BOM Creation',
                'verbose_name_plural': 'BOM Creations',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOMItemCreationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('RM', 'RM'), ('PACKING', 'Packing'), ('CONSUMABLE', 'Consumable')], max_length=16)),
                ('required_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.bomcreationmaster')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_item_creations', to='wpe_masters.itemmaster')),
            ],
            options={
                'verbose_name': 'BOM Item Creation',
                'verbose_name_plural': 'BOM Item Creations',
                'ordering': ['bom__code', 'item__item_code', 'id'],
            },
        ),
    ]
