# Generated by Django 6.0.4 on 2026-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_bomvariant_approved_at_bomvariant_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomvariant',
            name='access_password_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
