# Generated by Django 6.0.4 on 2026-06-01 10:00

import apps.production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_bomvariant_access_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecreationmaster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.production.models.profile_creation_image_upload_path),
        ),
    ]
