# Generated by Django 6.0.4 on 2026-06-01 11:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_add_image_to_profile_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecreationmaster',
            name='weight_per_piece',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
