# Generated by Django 6.0.4 on 2026-06-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productionorder_production_for'),
        ('production', '0009_weight_per_piece_required'),
    ]

    operations = [
    ]
