# Generated by Django 6.0.4 on 2026-06-02 04:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_productionoutputcapture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionoutputcapture',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='productionoutputcapture',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
    ]
