# Generated by Django 6.0.4 on 2026-06-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_alter_productionoutputcapture_quantity_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='extra_form_data',
            field=models.JSONField(blank=True, help_text='Stores additional form fields (stage, resources, plan rows, finished goods, etc.)', null=True),
        ),
    ]
