# Generated by Django 6.0.4 on 2026-06-03 10:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_productionorder_extra_form_data'),
        ('wpe_masters', '0009_ensure_blend_production_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bincreationmaster',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='bincreationmaster',
            name='capacity_uom',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('NOS', 'Nos')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='bincreationmaster',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_bins', to='wpe_masters.departmentmaster'),
        ),
    ]
