# Generated by Django 6.0.4 on 2026-06-03 14:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_alter_bincreationmaster_capacity_and_more'),
        ('wpe_masters', '0009_ensure_blend_production_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagcreationmaster',
            name='current_status',
            field=models.CharField(blank=True, choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied'), ('USED', 'Used')], default='FREE', max_length=16),
        ),
        migrations.AlterField(
            model_name='bagcreationmaster',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_bags', to='wpe_masters.departmentmaster'),
        ),
        migrations.AlterField(
            model_name='bagcreationmaster',
            name='standard_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
