# Generated by Django 6.0.4 on 2026-06-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_alter_bagcreationmaster_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bincreationmaster',
            name='current_status',
            field=models.CharField(blank=True, choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied'), ('HOLD', 'Hold')], default='FREE', max_length=16),
        ),
    ]
