# Generated by Django 6.0.4 on 2026-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_productionbatch_parent_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='stage',
            field=models.CharField(choices=[('AD', 'Raw Materials (AD)'), ('BL', 'Blending (BL)'), ('GL', 'Granulation (GL)'), ('PR', 'Production (PR)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='regrindmaterialentry',
            name='stage',
            field=models.CharField(choices=[('AD', 'Raw Materials (AD)'), ('BL', 'Blending (BL)'), ('GL', 'Granulation (GL)'), ('PR', 'Production (PR)')], max_length=10),
        ),
    ]
