# Generated by Django 6.0.4 on 2026-06-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_alter_productionbatch_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionoutputcapture',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productionoutputcapture',
            name='weight_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='productionoutputcapture',
            name='workstation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
