# Generated by Django 6.0.4 on 2026-06-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0021_productionoutputcapture_device_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionoutputcapture",
            name="bridge_client_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
