# Generated by Django 6.0.4 on 2026-07-07 11:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_item_external_item_id'),
        ('inventory', '0003_alter_productioninventorytransaction_stage'),
        ('production', '0022_productionoutputcapture_bridge_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLineConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_line_name', models.CharField(blank=True, db_column='line_name', max_length=200)),
                ('machine_name', models.CharField(blank=True, db_column='machine_name', max_length=200)),
                ('scan_code', models.CharField(db_column='scancode', db_index=True, max_length=200)),
                ('serial_no', models.CharField(db_column='baglot', db_index=True, max_length=100)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('weight_kg', models.DecimalField(db_column='weight', decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], db_index=True, default='ON', max_length=8)),
                ('connected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_line_connections', to=settings.AUTH_USER_MODEL)),
                ('disconnected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disconnected_line_connections', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_connections', to='Items.item')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_connections', to='production.productionmachine')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_connections', to='production.productionlinemaster')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_connections', to='production.productionorder')),
                ('source_inventory_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_connections', to='inventory.productioninventorytransaction')),
                ('source_production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_line_connections', to='production.productionorder')),
            ],
            options={
                'ordering': ['-connected_at', '-id'],
                'indexes': [models.Index(fields=['status', 'production_line'], name='prod_line_conn_status_idx'), models.Index(fields=['scan_code', 'status'], name='prod_line_conn_scan_idx'), models.Index(fields=['serial_no', 'status'], name='prod_line_conn_serial_idx')],
            },
        ),
    ]
