# Generated by Django 6.0.4 on 2026-07-14 08:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_productionlineconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('AD', 'Additive'), ('BL', 'Blending'), ('GL', 'Granulation'), ('PR', 'Production')], db_index=True, max_length=10, unique=True)),
                ('tare_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('uom', models.CharField(choices=[('KG', 'KG')], default='KG', max_length=16)),
            ],
            options={
                'verbose_name': 'Tare Master',
                'verbose_name_plural': 'Tare Masters',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
