# Generated by Codex on 2026-07-17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_productioninventorytransaction_stage"),
        ("production", "0023_productionlineconnection"),
        ("wpe_masters", "0013_scraptypemaster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionScrapCapture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                ("weight_kg", models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=14)),
                ("device_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("workstation_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("bridge_client_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("weight_source", models.CharField(blank=True, default="", max_length=32)),
                ("captured_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_scrap_captures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrap_captures",
                        to="inventory.productioninventorytransaction",
                    ),
                ),
                (
                    "line_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrap_captures",
                        to="production.productionlineconnection",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrap_captures",
                        to="production.productionorder",
                    ),
                ),
                (
                    "scrap_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scrap_captures",
                        to="wpe_masters.scraptypemaster",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scrap_captures",
                        to="production.productionbatch",
                    ),
                ),
                (
                    "source_inventory_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_scrap_captures",
                        to="inventory.productioninventorytransaction",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scrap_captures",
                        to="wpe_masters.warehousemaster",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at", "-id"],
                "indexes": [
                    models.Index(fields=["production_order", "captured_at"], name="prod_scrap_cap_ord_cap_idx"),
                    models.Index(fields=["source_batch", "captured_at"], name="prod_scrap_cap_batch_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productionscrapcapture",
            constraint=models.UniqueConstraint(fields=("production_order", "sequence"), name="prod_scrap_cap_ord_seq_uq"),
        ),
    ]
